sudo: required

language: generic

services:
  - docker

berfore_install:
  - echo "start creating an image with docekrfile"
  - docker build -t song7331/docker-react-app -f Dockerfile.dev

script:
  - docker run -e CI=true song7331/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test scuccess"
